### ISSUE TITLE
Cant compile Web.csproj

### ISSUE THREAD

**Issue by MoInMaRvZ** [Spijkervet/godfather#16]
Double "Content" elements are included. The .NET SDK contains standard "content" elements from your project directory. You can either remove these items from the project file, or set the EnableDefaultContentItems property to false if you want to explicitly include them in your project files.

C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.DefaultItems.targets	286

**Comment by tlmvipsml** [comment]
edit to 
https://pastebin.com/ZCDQRHqP
